name: SDVX Profile Extractor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 3,6' # Every Wednesday and Saturday at 7am UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: bamuel.com
    steps:
      - name: Set timezone to AEST
        run: sudo timedatectl set-timezone Australia/Sydney  # Set the timezone early in the workflow

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run SDVX Test
        run: |
          export TERM=xterm
          npx cypress run --spec cypress/e2e/sdvx.cy.js --browser chrome --env COOKIE_M573SSID=${{ secrets.COOKIE_M573SSID }}

      - name: Upload Cypress exports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-exports
          path: |
            cypress/exports/SDVXprofileData.json
          retention-days: 30
        continue-on-error: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.DEPLOY_HOST }}

      - name: Upload to webserver via SCP
        run: |
          scp -o StrictHostKeyChecking=no \
              cypress/exports/SDVXprofileData.json \
              ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}